### ISSUE TITLE
I promise i just have 1 more question

### ISSUE THREAD

**Issue by Coolykoen** [bakapear/stadia2xbox#3]
Is there a version you can build that doesnt check if its already running?

i want to try running 1, having it convert my controller to xinput, and then running another one, with a second stadia controller plugged in.

Im not directly asking for a new feature ;) sortof

anyway sorry for bothering you.

PS: the other options are not great... the one you send me a zip version for, seems to leak memory (it kept slowly consuming more, without me touching the pc for minutes)

**Comment by bakapear** [comment]
Multiple controllers are not supported. Removing the check so that multiple instances of the program can be run won't solve the problem because the second instance would just use the controller from the first instance.

Regarding the memory leak in StadiEm: It's not released yet anyways so that's to be expected

**Comment by bakapear** [comment]
@Coolykoen Quickly coded something to support multiple controllers: https://github.com/bakapear/stadia2xbox/releases/tag/1.2.0-alpha

Things to note:
- After plugging in the controller you have to click refresh manually
- Each device refresh can only add 1 controller. Which means if you have for example 4 controllers you want to connect you'd have to click refresh 4 times (or 3 if you count the automatic refresh on program startup). I will definitely change that to just add all available controllers one day... But for now that should be good enough for your needs?

I have no idea if it works as I don't have more than one stadia controller to test this, so let me know if it works!

**Comment by Coolykoen** [comment]
Wow... thanks for taking the time, you're a legend ^^
I'll test it tonight, and for me manual refresh is also totally fine

**Comment by Coolykoen** [comment]
Well, as an update:
I have not tested thoroughly, as i simply dont have high needs for it. However.. it works!

It works perfectly, i just plugged in both controllers, pressed refresh, and bam, 2 controllers both functioning as expected!

**Comment by Coolykoen** [comment]
To add to my last message:
I will still be using the normal release for my script to auto start stadia2xbox whenever i plug in the controller.
But for those Mario Party times and stuff, this version is great. ^^
