### ISSUE TITLE
Windows 11: "cannot access the file because it is being used"

### ISSUE THREAD

**Issue by CodingWill0** [bakapear/stadia2xbox#4]
![image](https://user-images.githubusercontent.com/38038438/150393427-9ded5ea9-030f-410c-a3ae-5a4cbf6693ca.png)
Worked fine with Windows 10. I rebooted, closed all programs, etc etc. Nothing worked. On Windows 10, it worked.
I guess Windows 11 broke it.

**Comment by bakapear** [comment]
Seems to be the same issue like in #1?

Either the [powershell cmd](https://github.com/bakapear/stadia2xbox/blob/b44cc234626ebbb10efbeb4459800c7e60653215/src/stadia/stadia.go#L55-L59) that should re-enable the device won't work on Win11 or that method itself is not working to get exclusive access anymore.

My machine doesn't support Win11 so I can't debug this myself.

**Comment by CodingWill0** [comment]
damn, sorry, thought the previous report was on Windows 10 (since it was not specified in the comment). On Windows 10 terminating processes was enough :)
Thanks.
