### ISSUE TITLE
REQUEST: multi-controller support

### ISSUE THREAD

**Issue by GreenMan36** [bakapear/stadia2xbox#6]
I have about 5 controllers but its a pain in the _ss to connect them all because you have to do some hacky stuff to get it to work properly with bluetooth enabled.

**Comment by bakapear** [comment]
I've added multiple controller support via USB, didnt look into bluetooth as it's a recent addition to the controller. Eitherway I can't test any of those because I sadly don't have more than 1 controller to work with.

**Comment by GreenMan36** [comment]
I was unable to test multi-controller support on bluetooth because of #5 but I assume it doesn't work because of https://github.com/71/stadiacontroller/issues/11

_Maybe someone else can verify stadia2xbox works, including multi-controller on bluetooth?_
